### PR TITLE
corrected rand! for mutable static arrays and moved them to an extension

### LINKED ISSUE #27: missing arguments in rand! methods for StaticArrays
The `rand!` methods for StaticArrays beginning on [line 398 of api.jl](https://github.com/JuliaSIMD/VectorizedRNG.jl/blob/c34cf44b11711a8acbf2032ce6dde80f08f3871a/src/api.jl#L398) don't define  α,  β, and  γ, but use them in the call to `samplevector!`.

### PR DESCRIPTION
**Pull request by schrimpf**
Fixes #27 

A couple things of note:

- I removed methods for immutable `SArray`s, since I think it's just not possible to modify them in place
- I removed the dependency on `StrideArraysCore`. It was only used to create `Ptr(x)` and I don't think it's needed.

### CODE REVIEW

**Comment by chriselrod** [comment]
The point of the `PtrArray` is to potentially avoid allocations.
Julia does not have proper escape analysis, so it conservatively heap allocates unnecessarily. `PtrArray` with `GC.@preserve` is a workaround.

`MArray <: StaticArray` and `SArray <: StaticArray`.
`MArray` is mutable, but `SArray` is not. Other hypothetical `StaticArray`s are mutable.

I don't really use this with `StaticArray`s, though, and we can blame current limitations of Julia's compiler for the allocations, so I'm okay merging this.

**Comment by chriselrod** [comment]
The point of the `PtrArray` is to potentially avoid allocations.
Julia does not have proper escape analysis, so it conservatively heap allocates unnecessarily. `PtrArray` with `GC.@preserve` is a workaround.

`MArray <: StaticArray` and `SArray <: StaticArray`.
`MArray` is mutable, but `SArray` is not. Other hypothetical `StaticArray`s are mutable.

I don't really use this with `StaticArray`s, though, and we can blame current limitations of Julia's compiler for the allocations, so I'm okay merging this.

**Comment by schrimpf** [comment]
This last change is about the best I can do. I do not understand the failed Aqua tests on version 1.6, and cannot fix them. They do not seem to matter anyway.

**Comment by chriselrod** [comment]
> This last change is about the best I can do. I do not understand the failed Aqua tests on version 1.6, and cannot fix them. They do not seem to matter anyway.

I wouldn't worry about them either.

**Pull request merged**
